---

- name: apt-key adv --keyserver
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  sudo: yes
  tags: mongodb

- name: add deb to mongodb-org-3.0.list
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  tags: mongodb

- name: apt-get install mongodb
  apt: name=mongodb-org state=installed update_cache=yes
  sudo: yes
  tags: mongodb

- name: apt-get install mongodb-tools
  apt: name={{ item }} state=installed
  with_items:
  - mongodb-org={{ mongodb_version }}
  - mongodb-org-server={{ mongodb_version }}
  - mongodb-org-shell={{ mongodb_version }}
  - mongodb-org-mongos={{ mongodb_version }}
  - mongodb-org-tools={{ mongodb_version }}
  sudo: yes
  tags: mongodb

- name: fix mongodb version
  shell: echo "{{ item }} hold" | sudo dpkg --set-selections
  with_items:
  - mongodb-org
  - mongodb-org-server
  - mongodb-org-shell
  - mongodb-org-mongos
  - mongodb-org-tools
  tags: mongodb
